// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudOSLoginV1
import GoogleCloudOSLoginCommon
import GoogleCloudWKT

func sample(userId: String, fingerprintId: String, ) async throws {
  let client = try GoogleCloudOSLoginV1.OsLoginServiceClient()
  let response = try await client.getSshPublicKey(
    request: GetSshPublicKeyRequest()
      .with {
        $0.name = "users/\(userId)/sshPublicKeys/\(fingerprintId)"
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      try await sample(userId: "[placeholder]", fingerprintId: "[placeholder]", )
    } catch {
      print("Error: \(error)")
    }
  }
}
