// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleCloudOSLoginCommon
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request message for importing an SSH public key.
public struct ImportSshPublicKeyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The unique ID for the user in format `users/{user}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The SSH public key and expiration time.
  public var sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey? = nil

  /// The project ID of the Google Cloud Platform project.
  public var projectId: Swift.String = Swift.String()

  /// Optional. The regions to which to assert that the key was written.
  /// If unspecified, defaults to all regions.
  /// Regions are listed at https://cloud.google.com/about/locations#region.
  public var regions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportSshPublicKeyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportSshPublicKeyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let sshPublicKey = CodingKeys(stringValue: "sshPublicKey")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let regions = CodingKeys(stringValue: "regions")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "sshPublicKey",
      "projectId",
      "regions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.sshPublicKey = try container.decodeIfPresent(
      GoogleCloudOSLoginCommon.SshPublicKey.self, forKey: .sshPublicKey)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .regions) {
      self.regions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.sshPublicKey, forKey: .sshPublicKey)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.regions, forKey: .regions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oslogin.v1.ImportSshPublicKeyRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
