// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudOSLoginCommon
import GoogleCloudWkt

/// A request message for importing an SSH public key.
public struct ImportSshPublicKeyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique ID for the user in format `users/{user}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The SSH public key and expiration time.
  public var sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey? = nil

  /// The project ID of the Google Cloud Platform project.
  public var projectId: Swift.String = Swift.String()

  /// Optional. The regions to which to assert that the key was written.
  /// If unspecified, defaults to all regions.
  /// Regions are listed at https://cloud.google.com/about/locations#region.
  public var regions: [Swift.String] = []

  /// Initialize a new instance of `ImportSshPublicKeyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportSshPublicKeyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oslogin.v1.ImportSshPublicKeyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
