// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudOSLoginCommon
import GoogleCloudWkt

/// The user profile information used for logging in to a virtual machine on
/// Google Compute Engine.
public struct LoginProfile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. A unique user ID.
  public var name: Swift.String = Swift.String()

  /// The list of POSIX accounts associated with the user.
  public var posixAccounts: [GoogleCloudOSLoginCommon.PosixAccount] = []

  /// A map from SSH public key fingerprint to the associated key object.
  public var sshPublicKeys: [Swift.String: GoogleCloudOSLoginCommon.SshPublicKey] = [:]

  /// Initialize a new instance of `LoginProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoginProfile().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oslogin.v1.LoginProfile"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
