// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudOSLoginCommon
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol OsLoginServiceStub {
    func createSshPublicKey(
      request: CreateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    func deletePosixAccount(
      request: DeletePosixAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func deleteSshPublicKey(
      request: DeleteSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getLoginProfile(
      request: GetLoginProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.LoginProfile

    func getSshPublicKey(
      request: GetSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    func importSshPublicKey(
      request: ImportSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse

    func updateSshPublicKey(
      request: UpdateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey
  }

  class OsLoginServiceTransport: OsLoginServiceStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://oslogin.googleapis.com")
    }

    public func createSshPublicKey(
      request: CreateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/sshPublicKeys"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.sshPublicKey {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudOSLoginCommon.SshPublicKey.self, from: data)
    }

    public func deletePosixAccount(
      request: DeletePosixAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func deleteSshPublicKey(
      request: DeleteSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func getLoginProfile(
      request: GetLoginProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.LoginProfile {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/loginProfile"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.projectId, prefix: "projectId"))
      query.append(contentsOf: try encoder.encode(request.systemId, prefix: "systemId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudOSLoginV1.LoginProfile.self, from: data)
    }

    public func getSshPublicKey(
      request: GetSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudOSLoginCommon.SshPublicKey.self, from: data)
    }

    public func importSshPublicKey(
      request: ImportSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0):importSshPublicKey"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.projectId, prefix: "projectId"))
      query.append(contentsOf: try encoder.encode(request.regions, prefix: "regions"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.sshPublicKey {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudOSLoginV1.ImportSshPublicKeyResponse.self, from: data)
    }

    public func updateSshPublicKey(
      request: UpdateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.sshPublicKey {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudOSLoginCommon.SshPublicKey.self, from: data)
    }
  }
}
