// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudOSLoginCommon
import GoogleCloudWKT
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class OsLoginServiceRetry: OsLoginServiceStub {
    let inner: any OsLoginServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any OsLoginServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createSshPublicKey(
      request: CreateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSshPublicKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOSLoginCommon.SshPublicKey
          in
          return try await self.inner.createSshPublicKey(request: r, options: o)
        })
    }

    public func deletePosixAccount(
      request: DeletePosixAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePosixAccountRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deletePosixAccount(request: r, options: o)
        })
    }

    public func deleteSshPublicKey(
      request: DeleteSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSshPublicKeyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSshPublicKey(request: r, options: o)
        })
    }

    public func getLoginProfile(
      request: GetLoginProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.LoginProfile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLoginProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOSLoginV1.LoginProfile
          in
          return try await self.inner.getLoginProfile(request: r, options: o)
        })
    }

    public func getSshPublicKey(
      request: GetSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSshPublicKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOSLoginCommon.SshPublicKey
          in
          return try await self.inner.getSshPublicKey(request: r, options: o)
        })
    }

    public func importSshPublicKey(
      request: ImportSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ImportSshPublicKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse
          in
          return try await self.inner.importSshPublicKey(request: r, options: o)
        })
    }

    public func updateSshPublicKey(
      request: UpdateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSshPublicKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudOSLoginCommon.SshPublicKey
          in
          return try await self.inner.updateSshPublicKey(request: r, options: o)
        })
    }
  }
}
