// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudOSLoginCommon
import GoogleCloudWKT
import GoogleCloudGax

/// Cloud OS Login API
///
/// The Cloud OS Login API allows you to manage users and their associated SSH
/// public keys for logging into virtual machines on Google Cloud Platform.
///
/// @Snippet(path: "OsLoginServiceQuickstart")
public final class OsLoginServiceClient: Clients.OsLoginServiceProtocol, Sendable {
  let inner: any Clients.OsLoginServiceStub

  /// Creates a new `OsLoginServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.OsLoginServiceStub = try Clients.OsLoginServiceTransport(options)
    inner = Clients.OsLoginServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OsLoginServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create an SSH public key
  ///
  /// @Snippet(path: "OsLoginService_CreateSshPublicKey")
  public func createSshPublicKey(
    request: CreateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    try await self.inner.createSshPublicKey(request: request, options: options)
  }

  /// Deletes a POSIX account.
  ///
  /// @Snippet(path: "OsLoginService_DeletePosixAccount")
  public func deletePosixAccount(
    request: DeletePosixAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deletePosixAccount(request: request, options: options)
  }

  /// Deletes an SSH public key.
  ///
  /// @Snippet(path: "OsLoginService_DeleteSshPublicKey")
  public func deleteSshPublicKey(
    request: DeleteSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSshPublicKey(request: request, options: options)
  }

  /// Retrieves the profile information used for logging in to a virtual machine
  /// on Google Compute Engine.
  ///
  /// @Snippet(path: "OsLoginService_GetLoginProfile")
  public func getLoginProfile(
    request: GetLoginProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginV1.LoginProfile {
    try await self.inner.getLoginProfile(request: request, options: options)
  }

  /// Retrieves an SSH public key.
  ///
  /// @Snippet(path: "OsLoginService_GetSshPublicKey")
  public func getSshPublicKey(
    request: GetSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    try await self.inner.getSshPublicKey(request: request, options: options)
  }

  /// Adds an SSH public key and returns the profile information. Default POSIX
  /// account information is set when no username and UID exist as part of the
  /// login profile.
  ///
  /// @Snippet(path: "OsLoginService_ImportSshPublicKey")
  public func importSshPublicKey(
    request: ImportSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse {
    try await self.inner.importSshPublicKey(request: request, options: options)
  }

  /// Updates an SSH public key and returns the profile information. This method
  /// supports patch semantics.
  ///
  /// @Snippet(path: "OsLoginService_UpdateSshPublicKey")
  public func updateSshPublicKey(
    request: UpdateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    try await self.inner.updateSshPublicKey(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OsLoginServiceClient`.
  ///
  /// To mock `OsLoginServiceClient` change your functions to receive
  /// `some OsLoginServiceProtocol` or `any OsLoginServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OsLoginServiceProtocol {
    /// See `OsLoginServiceClient.createSshPublicKey`.
    func createSshPublicKey(request: CreateSshPublicKeyRequest) async throws
      -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.createSshPublicKey`.
    func createSshPublicKey(
      parent: Swift.String,
      sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.deletePosixAccount`.
    func deletePosixAccount(request: DeletePosixAccountRequest) async throws

    /// See `OsLoginServiceClient.deletePosixAccount`.
    func deletePosixAccount(
      name: Swift.String,
    ) async throws

    /// See `OsLoginServiceClient.deleteSshPublicKey`.
    func deleteSshPublicKey(request: DeleteSshPublicKeyRequest) async throws

    /// See `OsLoginServiceClient.deleteSshPublicKey`.
    func deleteSshPublicKey(
      name: Swift.String,
    ) async throws

    /// See `OsLoginServiceClient.getLoginProfile`.
    func getLoginProfile(request: GetLoginProfileRequest) async throws
      -> GoogleCloudOSLoginV1.LoginProfile

    /// See `OsLoginServiceClient.getLoginProfile`.
    func getLoginProfile(
      name: Swift.String,
    ) async throws -> GoogleCloudOSLoginV1.LoginProfile

    /// See `OsLoginServiceClient.getSshPublicKey`.
    func getSshPublicKey(request: GetSshPublicKeyRequest) async throws
      -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.getSshPublicKey`.
    func getSshPublicKey(
      name: Swift.String,
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.importSshPublicKey`.
    func importSshPublicKey(request: ImportSshPublicKeyRequest) async throws
      -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse

    /// See `OsLoginServiceClient.importSshPublicKey`.
    func importSshPublicKey(
      parent: Swift.String,
      sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
    ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse

    /// See `OsLoginServiceClient.importSshPublicKey`.
    func importSshPublicKey(
      parent: Swift.String,
      sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
      projectId: Swift.String,
    ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse

    /// See `OsLoginServiceClient.updateSshPublicKey`.
    func updateSshPublicKey(request: UpdateSshPublicKeyRequest) async throws
      -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.updateSshPublicKey`.
    func updateSshPublicKey(
      name: Swift.String,
      sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.updateSshPublicKey`.
    func updateSshPublicKey(
      name: Swift.String,
      sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.createSshPublicKey`.
    func createSshPublicKey(
      request: CreateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.deletePosixAccount`.
    func deletePosixAccount(
      request: DeletePosixAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `OsLoginServiceClient.deleteSshPublicKey`.
    func deleteSshPublicKey(
      request: DeleteSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `OsLoginServiceClient.getLoginProfile`.
    func getLoginProfile(
      request: GetLoginProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.LoginProfile

    /// See `OsLoginServiceClient.getSshPublicKey`.
    func getSshPublicKey(
      request: GetSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey

    /// See `OsLoginServiceClient.importSshPublicKey`.
    func importSshPublicKey(
      request: ImportSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse

    /// See `OsLoginServiceClient.updateSshPublicKey`.
    func updateSshPublicKey(
      request: UpdateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey
  }
}

// Default implementations
extension Clients.OsLoginServiceProtocol {
  public func createSshPublicKey(request: CreateSshPublicKeyRequest) async throws
    -> GoogleCloudOSLoginCommon.SshPublicKey
  {
    try await self.createSshPublicKey(request: request, options: .init())
  }

  public func createSshPublicKey(
    request: CreateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSshPublicKey(
    parent: Swift.String,
    sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    let request = CreateSshPublicKeyRequest().with {
      $0.parent = parent
      $0.sshPublicKey = sshPublicKey
    }
    return try await self.createSshPublicKey(request: request)
  }

  public func deletePosixAccount(request: DeletePosixAccountRequest) async throws {
    try await self.deletePosixAccount(request: request, options: .init())
  }

  public func deletePosixAccount(
    request: DeletePosixAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deletePosixAccount(
    name: Swift.String,
  ) async throws {
    let request = DeletePosixAccountRequest().with {
      $0.name = name
    }
    try await self.deletePosixAccount(request: request)
  }

  public func deleteSshPublicKey(request: DeleteSshPublicKeyRequest) async throws {
    try await self.deleteSshPublicKey(request: request, options: .init())
  }

  public func deleteSshPublicKey(
    request: DeleteSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSshPublicKey(
    name: Swift.String,
  ) async throws {
    let request = DeleteSshPublicKeyRequest().with {
      $0.name = name
    }
    try await self.deleteSshPublicKey(request: request)
  }

  public func getLoginProfile(request: GetLoginProfileRequest) async throws
    -> GoogleCloudOSLoginV1.LoginProfile
  {
    try await self.getLoginProfile(request: request, options: .init())
  }

  public func getLoginProfile(
    request: GetLoginProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginV1.LoginProfile {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getLoginProfile(
    name: Swift.String,
  ) async throws -> GoogleCloudOSLoginV1.LoginProfile {
    let request = GetLoginProfileRequest().with {
      $0.name = name
    }
    return try await self.getLoginProfile(request: request)
  }

  public func getSshPublicKey(request: GetSshPublicKeyRequest) async throws
    -> GoogleCloudOSLoginCommon.SshPublicKey
  {
    try await self.getSshPublicKey(request: request, options: .init())
  }

  public func getSshPublicKey(
    request: GetSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSshPublicKey(
    name: Swift.String,
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    let request = GetSshPublicKeyRequest().with {
      $0.name = name
    }
    return try await self.getSshPublicKey(request: request)
  }

  public func importSshPublicKey(request: ImportSshPublicKeyRequest) async throws
    -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse
  {
    try await self.importSshPublicKey(request: request, options: .init())
  }

  public func importSshPublicKey(
    request: ImportSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func importSshPublicKey(
    parent: Swift.String,
    sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
  ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse {
    let request = ImportSshPublicKeyRequest().with {
      $0.parent = parent
      $0.sshPublicKey = sshPublicKey
    }
    return try await self.importSshPublicKey(request: request)
  }

  public func importSshPublicKey(
    parent: Swift.String,
    sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
    projectId: Swift.String,
  ) async throws -> GoogleCloudOSLoginV1.ImportSshPublicKeyResponse {
    let request = ImportSshPublicKeyRequest().with {
      $0.parent = parent
      $0.sshPublicKey = sshPublicKey
      $0.projectId = projectId
    }
    return try await self.importSshPublicKey(request: request)
  }

  public func updateSshPublicKey(request: UpdateSshPublicKeyRequest) async throws
    -> GoogleCloudOSLoginCommon.SshPublicKey
  {
    try await self.updateSshPublicKey(request: request, options: .init())
  }

  public func updateSshPublicKey(
    request: UpdateSshPublicKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSshPublicKey(
    name: Swift.String,
    sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    let request = UpdateSshPublicKeyRequest().with {
      $0.name = name
      $0.sshPublicKey = sshPublicKey
    }
    return try await self.updateSshPublicKey(request: request)
  }

  public func updateSshPublicKey(
    name: Swift.String,
    sshPublicKey: GoogleCloudOSLoginCommon.SshPublicKey?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudOSLoginCommon.SshPublicKey {
    let request = UpdateSshPublicKeyRequest().with {
      $0.name = name
      $0.sshPublicKey = sshPublicKey
      $0.updateMask = updateMask
    }
    return try await self.updateSshPublicKey(request: request)
  }
}
